apiVersion: batch/v1
kind: Job
metadata:
  name: create-admin
  namespace: rice
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: create-admin
          image: rice-soft-backend:latest
          imagePullPolicy: Never
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
          envFrom:
            - secretRef:
                name: backend-env
          command: ["node", "dist/scripts/create-admin.js"]


